### ISSUE TITLE
proc 內或許可以加入 vcruntime140_1d.dll 檔案

### ISSUE THREAD

**Issue by jayin92** [Su-Terry/Judge#1]
`verify.exe` 需要 `vcruntime140_1d.dll` 才能執行
而這個檔案需要額外安裝 Visual Studio，若沒有安裝 VS 就無法執行 judge。或許可以直接將此 DLL 檔放在資料夾中。

[DLL 下載連結](https://www.dll-files.com/vcruntime140_1d.dll.html)

**Comment by Su-Terry** [comment]
> `verify.exe` 需要 `vcruntime140_1d.dll` 才能執行 而這個檔案需要額外安裝 Visual Studio，若沒有安裝 VS 就無法執行 judge。或許可以直接將此 DLL 檔放在資料夾中。
> 
> [DLL 下載連結](https://www.dll-files.com/vcruntime140_1d.dll.html)

Thx, the new release without that problem is currently available with version v1.0.2.

**Comment by jayin92** [comment]
Okay, I'll close this issue.
